Setup state management & caching
Crypto-Capable/ambassadors-dao-ui pull request #11
Opened 2022-04-08 07:03 UTC by pratham15

Added caching and state management to all payout items
Divided payout index pages into two components, a representational head & list of items
Removed unnecessary imports

2022-04-08 08:42 UTC, siddharthborderwala requested changes
Good work from your side, not many changes required, except putting the pagination blocks back in.

You are getting better 🥳

2022-04-08 08:42 UTC, siddharthborderwala commented on atoms/index.ts
> +	{} as Record<number,CacheEntry< Payout<ReferralType>>>
```ts
{} as Record<number, CacheEntry<Payout<ReferralType>>>
```

2022-04-08 08:42 UTC, siddharthborderwala commented on hooks/payout-hooks.ts
> +export const useMiscellanea: usePayoutHook<MiscellaneousType> = ({
Ooh did not know Miscellaneous' plural is this, nice!

Shouldn't this one be useMiscelaneous and the above one be useMiscellanea?

2022-04-08 08:42 UTC, siddharthborderwala commented on hooks/payout-hooks.ts
> +  const data = useMemo(() => {
leave a line before this

2022-04-08 08:42 UTC, siddharthborderwala commented on hooks/payout-hooks.ts
> +};
So this file has a lot of code repetition, there is a simple way to refactor all of this. Think about it and if you can't figure it out, ask me.

2022-04-08 08:42 UTC, siddharthborderwala commented on pages/dashboard/bounties/index.tsx
> -      {bounties?.length == limit && (
We need to put this block of code back in the component for pagination. Do this for the rest of the pages with list. I am sorry I forgot to mention this earlier

2022-04-08 10:31 UTC, pratham15 commented on hooks/payout-hooks.ts
> +export const useMiscellanea: usePayoutHook<MiscellaneousType> = ({
Ah yes, I've reversed the names

2022-04-11 14:49 UTC, siddharthborderwala reviewed
Ok

2022-04-11 14:50 UTC, siddharthborderwala approved these changes

2022-04-11 14:56 UTC, merged